In [99]:
import keras
keras.__version__
import numpy as np
np.__version__
from keras.datasets import reuters as dataset
from keras.preprocessing.sequence import pad_sequences
import numpy as np

In [100]:
# Primer hyperparámetro
num_words=30000

(training_data, training_targets), (testing_data, testing_targets) = dataset.load_data(num_words=num_words+2)
data = np.concatenate((training_data, testing_data), axis=0)
targets = np.concatenate((training_targets, testing_targets), axis=0)

/home/j3nnn1/anaconda3/envs/nlp_deep/lib/python3.7/site-packages/keras/datasets/reuters.py:85: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x_train, y_train = np.array(xs[:idx]), np.array(labels[:idx])
/home/j3nnn1/anaconda3/envs/nlp_deep/lib/python3.7/site-packages/keras/datasets/reuters.py:86: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x_test, y_test = np.array(xs[idx:]), np.array(labels[idx:])


In [101]:
print(data)
print('\n')
print('# of Rows: {}', len(data))
print('# of Classes: {}', max(training_targets) + 1)

[list([1, 27595, 28842, 8, 43, 10, 447, 5, 25, 207, 270, 5, 3095, 111, 16, 369, 186, 90, 67, 7, 89, 5, 19, 102, 6, 19, 124, 15, 90, 67, 84, 22, 482, 26, 7, 48, 4, 49, 8, 864, 39, 209, 154, 6, 151, 6, 83, 11, 15, 22, 155, 11, 15, 7, 48, 9, 4579, 1005, 504, 6, 258, 6, 272, 11, 15, 22, 134, 44, 11, 15, 16, 8, 197, 1245, 90, 67, 52, 29, 209, 30, 32, 132, 6, 109, 15, 17, 12])
 list([1, 3267, 699, 3434, 2295, 56, 16784, 7511, 9, 56, 3906, 1073, 81, 5, 1198, 57, 366, 737, 132, 20, 4093, 7, 19261, 49, 2295, 13415, 1037, 3267, 699, 3434, 8, 7, 10, 241, 16, 855, 129, 231, 783, 5, 4, 587, 2295, 13415, 2, 775, 7, 48, 34, 191, 44, 35, 1795, 505, 17, 12])
 list([1, 53, 12, 284, 15, 14, 272, 26, 53, 959, 32, 818, 15, 14, 272, 26, 39, 684, 70, 11, 14, 12, 3886, 18, 180, 183, 187, 70, 11, 14, 102, 32, 11, 29, 53, 44, 704, 15, 14, 19, 758, 15, 53, 959, 47, 1013, 15, 14, 19, 132, 15, 39, 965, 32, 11, 14, 147, 72, 11, 180, 183, 187, 44, 11, 14, 102, 19, 11, 123, 186, 90, 67, 960, 4, 78, 13, 68, 467, 511, 

In [102]:
import numpy as np
import pandas as pd
type(data)
#narray to dataframe
dfData = pd.DataFrame(data)
type(dfData)
dfData.describe()

0
count                                               11228
unique                                              10439
top     [1, 9777, 9805, 71, 8, 25, 9455, 71, 323, 23, ...
freq                                                    6

In [103]:
import pandas as pd
type(targets)
#narray to dataframe
dfTarget = pd.DataFrame(targets)
type(dfTarget)
dfTarget.describe()


0
count  11228.000000
mean       8.890720
std        9.153068
min        0.000000
25%        3.000000
50%        4.000000
75%       14.000000
max       45.000000

In [104]:
# Tengo 46 categorías: 
num_categories = len(np.unique(targets))
print("Categories:", np.unique(targets))
# Tengo num_words palabras únicas en el vocabulario
print("Number of unique words:", len(np.unique(np.hstack(data))))

Categories: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45]
Number of unique words: 30000


In [105]:

# Longitudes promedio de los comentarios de las películas
length = [len(i) for i in data]
print("Average Review length:", np.mean(length))
print("Standard Deviation:", round(np.std(length)))


Average Review length: 145.96419665122906
Standard Deviation: 146


In [106]:
i = 3
print("Label:", targets[i])
# Las comentarios ya están preprocesados
print(data[i])
print("tiene N %s palabras", np.shape(data[i]))

Label: 4
[1, 4, 686, 867, 558, 4, 37, 38, 309, 2276, 465, 893, 3541, 114, 2902, 69, 312, 35, 15, 7, 335, 1679, 21, 25, 3675, 19519, 3498, 58, 69, 68, 493, 5, 25, 465, 377, 2430, 4, 293, 1172, 739, 4379, 8, 7, 1510, 1131, 13, 899, 6, 4, 990, 309, 415, 4519, 6920, 645, 3916, 791, 5, 4379, 75, 8, 24, 10, 1311, 4677, 5, 344, 756, 7, 29700, 231, 9691, 2603, 1413, 43, 509, 43, 68, 327, 5, 14560, 3498, 297, 638, 73, 430, 22, 4, 580, 7, 48, 41, 30, 14021, 136, 4, 344, 298, 4, 580, 40, 344, 5078, 23457, 291, 1488, 10, 3148, 5, 231, 6250, 1308, 5, 8250, 7043, 21, 18776, 1622, 990, 309, 415, 265, 5992, 8945, 1149, 9118, 27677, 4, 344, 9691, 756, 3729, 14560, 4667, 28400, 3249, 28, 10, 2190, 24, 77, 41, 682, 10, 4851, 2048, 7, 4, 5540, 2926, 1598, 22, 370, 5954, 7541, 5, 54, 5232, 1685, 2916, 10, 1571, 946, 60, 51, 3249, 5249, 4, 73, 2135, 669, 4, 580, 64, 10, 4280, 6, 16319, 25, 482, 35, 150, 377, 2430, 7, 10, 21743, 836, 29981, 4730, 6920, 5, 4379, 12711, 16799, 3541, 8, 4, 344, 291, 29693, 298,

In [107]:
from keras.layers import Dense, Dropout
from keras.models import Sequential

In [108]:
num_classes = 46
import tensorflow as tf
y_all_one_hot_enc = tf.keras.utils.to_categorical(targets, num_classes)
print(y_all_one_hot_enc)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [109]:
print(len(data[1]))

56


In [110]:


import numpy as np
def vectorize_sequences(sequences, dimension=30002):
    results = np.zeros((len(sequences), dimension))
    for i, sequence in enumerate(sequences):
        for j in sequence:
            results[i, j] = 1.
    return results


def to_one_hot(labels, dimension=46):
    results = np.zeros((len(labels), dimension))
    for i, label in enumerate(labels):
        results[i, label] = 1.
    return results



In [111]:
num_classes = 46
import tensorflow as tf
y_all_one_hot_enc = tf.keras.utils.to_categorical(targets, num_classes)
print(y_all_one_hot_enc)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [112]:
np.shape(y_all_one_hot_enc)

(11228, 46)

In [113]:
train = vectorize_sequences(data)

In [258]:
np.shape(data[0])

(87,)

In [114]:
np.shape(train)

(11228, 30002)

In [115]:
num_classes = 46

In [116]:
len(train[0])

30002

In [117]:
len(train[0])

30002

In [259]:

model = Sequential()
salida_densa = 350
input_shape = len(train[0])
#input_shape = max num words 

model.add(Dense(salida_densa, input_shape=(input_shape,), activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))

In [260]:
model.compile(loss='categorical_crossentropy', optimizer='rmsprop', metrics=['accuracy'])

In [261]:


# Lets explore the model
# http://keras.io/models/about-keras-models/
print(model.summary()) #  summary representation of your model



Model: "sequential_37"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_97 (Dense)             (None, 350)               10501050  
_________________________________________________________________
dropout_19 (Dropout)         (None, 350)               0         
_________________________________________________________________
dense_98 (Dense)             (None, 64)                22464     
_________________________________________________________________
dense_99 (Dense)             (None, 46)                2990      
Total params: 10,526,504
Trainable params: 10,526,504
Non-trainable params: 0
_________________________________________________________________
None


In [262]:
np.shape(train[3])

(30002,)

In [263]:
np.shape(y_all_one_hot_enc[0])
print(y_all_one_hot_enc[0])

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [264]:
x_val = train[:1000]
partial_x_train = train[1000:]
y_val = y_all_one_hot_enc[:1000]
partial_y_train = y_all_one_hot_enc[1000:]

In [265]:
batch_size = 32
nb_epoch = 10

result = model.fit(train, y_all_one_hot_enc, epochs=nb_epoch,  batch_size=batch_size)
#result = model.fit(train, y_all_one_hot_enc, epochs=nb_epoch, batch_size=batch_size, verbose=1, validation_data=(x_val, y_val))
#result = model.fit(train, y_all_one_hot_enc, epochs=nb_epoch, batch_size=batch_size, verbose=1, validation_split=0.1)



Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/10
11228/11228 [==============================] - 46s 4ms/step - loss: 1.3072 - acc: 0.7105
Epoch 2/10
11228/11228 [==============================] - 44s 4ms/step - loss: 0.7296 - acc: 0.8424
Epoch 3/10
11228/11228 [==============================] - 44s 4ms/step - loss: 0.5350 - acc: 0.8855
Epoch 4/10
11228/11228 [==============================] - 44s 4ms/step - loss: 0.4318 - acc: 0.9098
Epoch 5/10
11228/11228 [==============================] - 44s 4ms/step - loss: 0.3699 - acc: 0.9241
Epoch 6/10
11228/11228 [==============================] - 44s 4ms/step - loss: 0.3379 - acc: 0.9311
Epoch 7/10
11228/11228 [==============================] - 44s 4ms/step - loss: 0.3224 - acc: 0.9347
Epoch 8/10
11228/11228 [==============================] - 47s 4ms/step - loss: 0.3050 - acc: 0.9378
Epoch 9/10
11228/11228 [==============================] - 48s 4ms/step - loss: 0.3005 - acc: 0.9396
Epoch 

In [ ]:
#%% md

# Armar una MLP usando Embeddings

In [267]:
# Armar una MLP usando Embeddings
from keras.layers import Embedding, Flatten, Dropout
from keras import optimizers

In [268]:

# Hyperparametro - Longitud máxima de comentario
maxlen=1000
# Cantidad de palabras totales contando las reservadas
nb_words=num_words+3
# Tamano del embedding. Es un hiperparámetro y puede modificarlo
embed_dim=128
salida_capa_densa = num_classes
dropout=0.5 # Hiperparámetro

model = Sequential()
model.add(Embedding(nb_words, embed_dim, input_length=maxlen, trainable=True))
model.add(Flatten())
#model.add(Dropout(dropout))
model.add(Dense(salida_capa_densa, activation='softmax'))


In [269]:
model.summary()

Model: "sequential_38"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 1000, 128)         3840384   
_________________________________________________________________
flatten_1 (Flatten)          (None, 128000)            0         
_________________________________________________________________
dense_100 (Dense)            (None, 46)                5888046   
Total params: 9,728,430
Trainable params: 9,728,430
Non-trainable params: 0
_________________________________________________________________


In [276]:
adam = optimizers.Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0)

model.compile(loss='categorical_crossentropy', optimizer=adam, metrics=['accuracy'])

In [277]:
np.shape(data[0])

(87,)

In [278]:
data = pad_sequences(data,maxlen=maxlen)

In [279]:
# Verificamos que todos tengan longitud 1000
print(len(data[0]))
print(np.array([len(d) for d in data]).var())

1000
0.0


In [280]:
data=np.array(data)

In [282]:
model.fit(data,y_all_one_hot_enc,batch_size=32,epochs=5)#,validation_split=0.2)

Epoch 1/5
11228/11228 [==============================] - 52s 5ms/step - loss: 1.7294 - acc: 0.5972
Epoch 2/5
11228/11228 [==============================] - 51s 5ms/step - loss: 0.7322 - acc: 0.8494
Epoch 3/5
11228/11228 [==============================] - 53s 5ms/step - loss: 0.4203 - acc: 0.9254
Epoch 4/5
11228/11228 [==============================] - 57s 5ms/step - loss: 0.3223 - acc: 0.9414
Epoch 5/5
11228/11228 [==============================] - 52s 5ms/step - loss: 0.2888 - acc: 0.9445


In [285]:
#%% md

# Armar una CNN
## Abajo hay un ejemplo de arquitectura

In [ ]:
#%%

# _________________________________________________________________
# Layer (type)                 Output Shape              Param #   
# =================================================================
# embedding_12 (Embedding)     (None, 1000, 32)          960096    
# _________________________________________________________________
# conv1d_7 (Conv1D)            (None, 1000, 64)          14400     
# _________________________________________________________________
# max_pooling1d_4 (MaxPooling1 (None, 500, 64)           0         
# _________________________________________________________________
# conv1d_8 (Conv1D)            (None, 500, 128)          57472     
# _________________________________________________________________
# global_max_pooling1d_4 (Glob (None, 128)               0         
# _________________________________________________________________
# dropout_4 (Dropout)          (None, 128)               0         
# _________________________________________________________________
# dense_19 (Dense)             (None, 46)                5934      
# =================================================================

In [293]:


from keras.layers import Embedding, Flatten, Dropout, Conv1D, MaxPooling1D
from keras import optimizers


# Cantidad de palabras totales contando las reservadas
nb_words=num_words+3
# Tamano del embedding. Es un hiperparámetro y puede modificarlo
embed_dim=128
salida_capa_densa = num_classes
dropout=0.5 # Hiperparámetro

model = Sequential()
model.add(Embedding(nb_words, embed_dim, input_length=maxlen, trainable=True))
model.add(Conv1D(filters=64, kernel_size=8, activation='relu' , input_shape = (maxlen,embed_dim)))
model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dropout(dropout))
model.add(Dense(salida_capa_densa, activation='softmax'))

In [294]:
model.summary()

Model: "sequential_41"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, 1000, 128)         3840384   
_________________________________________________________________
conv1d_2 (Conv1D)            (None, 993, 64)           65600     
_________________________________________________________________
max_pooling1d_2 (MaxPooling1 (None, 496, 64)           0         
_________________________________________________________________
flatten_2 (Flatten)          (None, 31744)             0         
_________________________________________________________________
dropout_21 (Dropout)         (None, 31744)             0         
_________________________________________________________________
dense_102 (Dense)            (None, 46)                1460270   
Total params: 5,366,254
Trainable params: 5,366,254
Non-trainable params: 0
___________________________________________

In [297]:
# MODIFIQUE HYPERPARAMS A GUSTO
adam = optimizers.Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0)

model.compile(loss='categorical_crossentropy', optimizer=adam, metrics=['accuracy'])

In [298]:
model.fit(data,y_all_one_hot_enc,batch_size=32,epochs=10,validation_split=0.2)

Train on 8982 samples, validate on 2246 samples
Epoch 1/10
8982/8982 [==============================] - 101s 11ms/step - loss: 0.5233 - acc: 0.8661 - val_loss: 1.4480 - val_acc: 0.7164
Epoch 2/10
8982/8982 [==============================] - 102s 11ms/step - loss: 0.4393 - acc: 0.8874 - val_loss: 1.5220 - val_acc: 0.7168
Epoch 3/10
8982/8982 [==============================] - 102s 11ms/step - loss: 0.3761 - acc: 0.9028 - val_loss: 1.6108 - val_acc: 0.7164
Epoch 4/10
8982/8982 [==============================] - 102s 11ms/step - loss: 0.3244 - acc: 0.9135 - val_loss: 1.6230 - val_acc: 0.7244
Epoch 5/10
8982/8982 [==============================] - 103s 11ms/step - loss: 0.2834 - acc: 0.9226 - val_loss: 1.6949 - val_acc: 0.7177
Epoch 6/10
8982/8982 [==============================] - 104s 12ms/step - loss: 0.2500 - acc: 0.9330 - val_loss: 1.7379 - val_acc: 0.7168
Epoch 7/10
8982/8982 [==============================] - 103s 11ms/step - loss: 0.2293 - acc: 0.9382 - val_loss: 1.7348 - val_acc: 